### ISSUE TITLE
LockingIterator should use fopen mode c

### ISSUE THREAD

**Issue by chx** [SuRaMoN/itertools#8]
$this->lockFp = fopen("{$this->dir}/$name", 'w+');
		flock($this->lockFp, LOCK_EX);

This is not atomic. Probably

		$this->lockFp = @fopen("{$this->dir}/$name", 'x');

would be better. On unlock, just delete the file.

**Comment by SuRaMoN** [comment]
No this would be a really bad way of dealing with locks. If the program crashes, the flock call wil automatically release its lock.
If you use fopen with 'x' modifier and the program crashes the file remains and no new processes can start.

the current code is atomic. you can easily test it by running the following code twice concurrently:
```
<?php

var_dump("opening");
$lockFp = fopen("lock", 'w+');
sleep(2);
var_dump("locking");
flock($lockFp, LOCK_EX);
var_dump("locked");
sleep(5);
fclose($lockFp);
var_dump("ready");
```
with the extra sleep functions the race conditons can be tested and in no circumstances can the locked parted by executed twice concurrently.

**Comment by chx** [comment]
Sure! While we are chatting (hi!) mind chiming in on itertools vs nikic/iter in https://www.drupal.org/node/2757489 ? Thanks much!
